services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/app
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "3301:80"
    depends_on:
      - php
    container_name: project_nginx

  php:
    build:
      context: .
      dockerfile: _docker/php/Dockerfile
    volumes:
      - ./:/app
    container_name: project_php